name: flutter_saver
description: "A Flutter package for saving images and downloadable links across all platforms with support for various formats."
version: 0.0.1+4
homepage: "https://github.com/SwanFlutter/flutter_saver"


platforms:
  android:
  ios:
  web:
  macos:
  windows:

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  
  
  flutter:
    sdk: flutter
  http: ^1.2.2
  path_provider: ^2.1.3
  external_path: ^2.0.1
  external_path_ios_mac: ^0.0.2
  device_info_plus: ^10.1.2
  path: ^1.8.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:


