name: flutter_saver
description: "A package to save image and files to downloads folder all platform."
version: 0.0.1
homepage: "https://github.com/SwanFlutter/flutter_saver"

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  
  external_path: ^1.0.3
  flutter:
    sdk: flutter
  http: ^1.2.2
  path_provider: ^2.1.3
  path_provider_foundation: ^2.4.0
  path_provider_platform_interface: ^2.1.2
  permission_handler: ^11.3.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:


