name: flutter_saver
description: "This Flutter package provides a powerful and versatile solution for saving camera images and downloadable links across all platforms. With support for various formats, it allows developers to store images and files efficiently in device memory."
version: 0.0.1
homepage: "https://github.com/SwanFlutter/flutter_saver"

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  
  
  flutter:
    sdk: flutter
  http: ^1.2.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  external_path: ^2.0.1
  external_path_ios_mac: ^0.0.1
  device_info_plus: ^10.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:


